### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by aoozdemir** [nasa/earthdata-search#1]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby2.1.0/bin/ruby.exe -r ./siteconf20150818-11932-hb24zj.rb extconf.rb
Command 'qmake -spec win32-g++ ' not available

Makefile not found

Gem files will remain installed in C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/bundler/gems/capybara-webkit-042822d7
c6f7 for inspection.
Results logged to C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/bundler/gems/extensions/x86-mingw32/2.1.0/capybara-web
kit-042822d7c6f7/gem_make.out
An error occurred while installing capybara-webkit (1.1.1), and Bundler cannot
continue.
Make sure that `gem install capybara-webkit -v '1.1.1'` succeeds before
bundling.
```

This is the error I get when I try to run `bundle install`. It seems like a common issue. I installed Qt libraries [(v5.5.0)](http://tver-soft.org/qt64), but it didn't work. Do you have a solution for this?

**External Links** *I've already checked these.*
> [Capybara Webkit Wiki](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit) 
> [Stackoverflow](http://stackoverflow.com/questions/11835260/cannot-install-rails-gem-capybara-webkit-in-windows)

**Comment by bilts** [comment]
It looks like `qmake` (usually distributed with Qt) isn't in your `PATH`.

**Comment by aoozdemir** [comment]
Yeah, I checked and did a clean install again for
* MinGW [Latest Release](http://sourceforge.net/projects/mingw/) and Qt [v4.8.5](https://download.qt.io/archive/qt/), 

even though it says **Only versions with W32API 3.13 are supported** It worked for capybara-webkit.

However, this time I'm having an issue with `kgio library`. Now that i found out **the kgio gem only builds and runs on Unix like systems (http://bogomips.org/kgio/) It uses functions which are not natively available on Windows[*](http://stackoverflow.com/questions/14483058/cant-bundle-install-kgio-error).** So I'll try some other time with another OS. I think, this closes the issue here for now. Thank you.

**Comment by bilts** [comment]
Sorry this isn't working for you. We all use Unix-like systems for development and have never tried running Earthdata Search on Windows. If you do have any luck, I'd be happy to hear about it.

For what it's worth, unicorn isn't a hard dependency for development. It should be just as easy to run on WEBrick or similar.
