### ISSUE TITLE
EDSC-2909: Create EDSCIcon component and implement react-icons

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1217]
### Description
Currently we use a font-awesome package from npm which imports Font Awesome as a font. To improve performance, we should replace this with an svg library like react-icons. We should create an Icon component which will dynamically import react-icons, allowing us to add/remove libraries as needed. The component should accept className, library, and icon as props. Initially, only the Font Awesome library will be used.

### Acceptance Criteria
- All instances of `<i>` icon elements replaced with EDSCIcon component
- No visual changes to current icons

**Comment by suhay** [comment]
Hey! Would like to grab this one.

**Comment by abbottry** [comment]
Awesome, we're here if you have any questions!
