### ISSUE TITLE
EDSC-2672: Lazy load Timeline component

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1219]
### Description
In an effort to improve initial load times, we should lazy load the Timeline component. We want to be sure to do this in a way that does not degrade the UX of the initial application load.

### Acceptance Criteria
- Timeline javascript is only loaded in pages that render the timeline (/search/granules, /project)

**Comment by sofiarivas** [comment]
Hi @mreese84 I need to take a closer look at the codebase but I think this could be accomplished with `React.suspense` https://web.dev/code-splitting-suspense/

If this is the case I can work on this issue 🙂

**Comment by trevorlang** [comment]
@sofiarivas, thats correct! We have React lazy/suspense implemented in a few other places throughout the application if you would like some ([prior art](https://github.com/nasa/earthdata-search/blob/acd1679e927089dd1a5cb34fa0fee2ab1f40b3c5/static/src/js/components/AccessMethod/AccessMethod.js))
