### ISSUE TITLE
EDSC-2910: Add keyboard shortcut to toggle granule filters

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1221]
### Description
Add keyboard shortcut to toggle granule filters when looking at granules. This should only be active when looking at /search/granules...

The `g` button should be used for this shortcut.

### Acceptance Criteria
- When on the granules page (/search/granules), hitting the `g` button on the keyboard toggles the granule filters panel active/inactive.
- When not on the granules page, hitting the `g` button on the keyboard has no impact on the application

**Comment by mreese84** [comment]
The commit for our first keyboard shortcut can be [found here](https://github.com/nasa/earthdata-search/commit/e58d0195f17441fca1e44ff9094368c3947464e3) (amongst a few other changes 😄 )

**Comment by bensun13** [comment]
I can handle this issue. Will have PR up in a few!
