### ISSUE TITLE
EDSC-2911: Add keyboard shortcut to toggle advanced search modal

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1222]
### Description
Add keyboard shortcut to toggle advanced search when on a page that supports search (/search, /search/granules).

The `a` button should be used for this shortcut.

### Acceptance Criteria
- When on a search supported page (/search, /search/granules), hitting the `a` button on the keyboard toggles the advanced search modal active/inactive.
- When not on a search supported page (/search, /search/granules), hitting the `a` button on the keyboard has no impact on the application.

**Comment by ilhan-mstf** [comment]
Hi, I would like to work on this issue, can you assign me it?

**Comment by mreese84** [comment]
The commit for our first keyboard shortcut can be [found here](https://github.com/nasa/earthdata-search/commit/e58d0195f17441fca1e44ff9094368c3947464e3) (amongst a few other changes 😄 )

**Comment by mreese84** [comment]
Before submitting a PR, please make sure you have a test for the functionality you've added. A unit test was added for our existing keyboard shortcut with [this PR](https://github.com/nasa/earthdata-search/pull/1232). Thank you!

**Comment by ilhan-mstf** [comment]
I have started development yesterday. I'll continue with unit tests today.
