### ISSUE TITLE
EDSC-2912: Add keyboard shortcut to focus on search bar

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1223]
### Description
Add keyboard shortcut to focus on the search bar input field when on a page that supports search (/search, /search/granules).

The `/` button should be used for this shortcut.

### Acceptance Criteria
- When on a search supported page (/search, /search/granules), hitting the `/` button on the keyboard focuses on the search input field.
- When not on a search supported page (/search, /search/granules), hitting the `/` button on the keyboard has no impact on the application.

**Comment by i-hardy** [comment]
Hi, I'd like to take this!

**Comment by mreese84** [comment]
Excellent. Go for it! Thank you for contributing.

**Comment by mreese84** [comment]
The commit for our first keyboard shortcut can be [found here](https://github.com/nasa/earthdata-search/commit/e58d0195f17441fca1e44ff9094368c3947464e3) (amongst a few other changes 😄 )
