### ISSUE TITLE
EDSC-2914: Add keyboard shortcut to toggle the timeline

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1225]
### Description
Add keyboard shortcut to toggle timeline when on a page that displays the timeline (/search/granules, /projects).

The `t` button should be used for this shortcut.

### Acceptance Criteria
- When on the granules or project page (/search/granules, /projects), hitting the `t` button on the keyboard toggles the timeline active/inactive.
- When not on the granules or project page, hitting the `t` button on the keyboard has no impact on the application
- Add `t: 'Toggle timeline'` to `KeyboardShortcutsModal.js `
- When a user is typing into any input field, hitting the `t` button does not trigger the shortcut

**Comment by adnansalik** [comment]
Hey, can I work on this?

**Comment by mreese84** [comment]
Go for it @adnansalik. There are a few keyboard shortcut issues that would be nice to all go in together if you're up for it.

**Comment by adnansalik** [comment]
Yes I noticed that, I will try to include all those issues. I'm really new to contributing so it might take a while but I'll keep you updated.

**Comment by mreese84** [comment]
We have 1 keyboard shortcut already. That was [committed here](https://github.com/nasa/earthdata-search/commit/e58d0195f17441fca1e44ff9094368c3947464e3)

**Comment by mreese84** [comment]
@adnansalik please note that there are several other people wanting to work the other keyboard shortcuts. So, please scope this commit to this one so we aren't stepping on toes.

**Comment by mreese84** [comment]
Before submitting a PR, please make sure you have a test for the functionality you've added. A unit test was added for our existing keyboard shortcut with [this PR](https://github.com/nasa/earthdata-search/pull/1232). Thank you!

**Comment by adnansalik** [comment]
Hey, I think I won't be able to get around this issue because something really urgent came up and I won't get enough time to work on it so I'm sorry and anyone can take this issue as I won't be working on it anymore.

**Comment by marisamorby** [comment]
I would like to work on this issue!

**Comment by mreese84** [comment]
Go for it @marisamorby!

**Comment by marisamorby** [comment]
Hi @mreese84! I realized while setting this up that it's a bit above my current ability. I got to the "you need to install postgres" step and realized I was really punching above my weight. 😬 

I'm sorry, but I'm going to throw this issue back in the pond for someone who's able to complete it.

**Comment by mreese84** [comment]
Gotcha @marisamorby, no worries.

**Comment by taismassaro** [comment]
I'd like to give it a try on this over the weekend if that's ok :)

**Comment by mfayaq** [comment]
Is this issue still open? Can I try? Or @taismassaro is on it?

**Comment by mreese84** [comment]
@mfayaq it is still open. If you want to give it a go, please do. Also, please note that after the last round of shortcut tickets were worked we had to go in and ensure typing the various shortcut keys _while typing in an input field_ did not trigger that shortcut. We will be checking to ensure that doesn't happen with this as well.

**Comment by taismassaro** [comment]
sorry I was waiting on a response to get started. but I guess you can go ahead then, @mfayaq

**Comment by mfayaq** [comment]
> @mfayaq it is still open. If you want to give it a go, please do. Also, please note that after the last round of shortcut tickets were worked we had to go in and ensure typing the various shortcut keys _while typing in an input field_ did not trigger that shortcut. We will be checking to ensure that doesn't happen with this as well.

Oh I kind of miss that one. I have checked in the new code. And followed the new implementation :)

**Comment by mfayaq** [comment]
> sorry I was waiting on a response to get started. but I guess you can go ahead then, @mfayaq

No issues @taismassaro , maybe next time :)
