### ISSUE TITLE
EDSC-2895: Direct download button not working for multi-file granules in list view

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1227]
### Description
Some collections consist of granules that are "multi-file" granules. In this case, clicking the "Download single granule data" button should display a dropdown of the available files to download. This is not working when a user is in the table view on the granules panel.

**Reproduction Steps**

1. Search for a collection that has multi-file granules and click on it to load granules (NSIDC-0481 Prod environment)
2. Click on the download icon in the list view and observe that multiple files appear
4. Switch to table view using the toggle in the top-right of the granules panel
5. Click on the download icon in the table view and observe that nothing happens

### Acceptance Criteria

1. Search for a collection that has multi-file granules and click on it to load granules (NSIDC-0481 in Prod)
2. Click on the download icon in the list view and observe that multiple files appear
3. Confirm that clicking on those links downloads the intended file
4. Switch to table view using the toggle at the top of the granules panel
5. Click on the download icon in the table view and observe that multiple files appear
6. Confirm that clicking on those links downloads the intended file

**Comment by saurabhdaware** [comment]
Hi, I would like give it a try

**Comment by mreese84** [comment]
Go for it! Good luck.

**Comment by saurabhdaware** [comment]
Hi, I did the frontend setup locally and I can see collections but when I open them to load granules, I'm getting error.

Do I have to setup backend and database as well? Is there any way where I can paste sample data (for testing purpose)? Thank you.

**Comment by abbottry** [comment]
Good morning! 

Thankfully, you do not need a database or any backend for this issue.

If you search for `NSIDC-0481` you'll see a couple of collections come up, here is a direct link to the first one: http://localhost:8080/search/granules?p=C1923703805-NSIDC_ECS&pg[0][gsk]=-start_date&q=NSIDC-0481&m=1.4210854715202004e-14!0!0!1!0!0%2C2&tl=1585925509!4!!

You can switch between the card view and table view using the small switcher: 

![Screen Shot 2020-10-03 at 10 56 59 AM](https://user-images.githubusercontent.com/174744/94994681-31c9a100-0567-11eb-97ab-059029e4607a.png)

Notice that from the 'card view' when I click the granule download button it shows a drop down, but when I am looking at the 'table view' it does not.

![Screen Shot 2020-10-03 at 10 56 10 AM](https://user-images.githubusercontent.com/174744/94994666-1199e200-0567-11eb-8862-c5cc39084e89.png)

![Screen Shot 2020-10-03 at 10 54 59 AM](https://user-images.githubusercontent.com/174744/94994658-ff1fa880-0566-11eb-87ac-7a86b385a613.png)

**Comment by saurabhdaware** [comment]
I'm actually tried that but getting this error in it for some reason:
![image](https://user-images.githubusercontent.com/30949385/94995499-497f4480-05bc-11eb-9716-e86de467b5b3.png)

I did `npm install` and `npm start`

**Comment by abbottry** [comment]
That’s odd. Try starting serverless offline (instructions are in the readme) and see if that helps.

**Comment by saurabhdaware** [comment]
Ok yay I found a workaround. So clicking on timeline below brought some results but font awesome icons didn't load. So Injected fontawesome in console and I can see a the dropdown part and table view icons now.
![image](https://user-images.githubusercontent.com/30949385/94997038-06c26a00-05c6-11eb-8b95-973c5035d10f.png)

I think this is enough to get it working for now.

> That’s odd. Try starting serverless offline (instructions are in the readme) and see if that helps.

Yup I'll check this too and let you know. Thank you for the help!

**Comment by saurabhdaware** [comment]
`serverless offline` did solve the network errors but this error is still there and I still can't see the results directly. 
![image](https://user-images.githubusercontent.com/30949385/94997153-05457180-05c7-11eb-88fb-ff2733b09091.png)

**Comment by abbottry** [comment]
Ah! I got it -- try now.

**Comment by saurabhdaware** [comment]
yay working now :D
