### ISSUE TITLE
EDSC-2515: Improve loading state for collection results

### ISSUE THREAD

**Issue by mreese84** [nasa/earthdata-search#1229]
Please review [Contribution.md](https://github.com/nasa/earthdata-search/blob/master/CONTRIBUTING.md) before contributing to this project.

### Description
We should implement a nicer loading state similar to the ones elsewhere in the application. Either the pulsing 3 ellipses (like when viewing download history) or the pulsing content skeleton (like on granules panel) will work.

### Acceptance Criteria

1. Loading state for collections is in line with loading states throughout the application.

**Comment by heykc** [comment]
Hey Mark! You can assign this one to me as well. Going to go with the skeleton anim because 
1) stays consistent with the particular panel and how granules' table and list layouts load, and; 
2) seems more fun 😉

**Comment by mreese84** [comment]
> Hey Mark! You can assign this one to me as well. Going to go with the skeleton anim because
> 
> 1. stays consistent with the particular panel and how granules' table and list layouts load, and;
> 2. seems more fun 😉

Ha! Go for it.
