### ISSUE TITLE
EDSC-3300: Change "Search for collections or topics" placeholder in keyword search

### ISSUE THREAD

**Issue by macrouch** [nasa/earthdata-search#1542]
Please review [Contribution.md](https://github.com/nasa/earthdata-search/blob/master/CONTRIBUTING.md) before contributing to this project.

### Description
The freetext placeholder on Earthdata Search says "Search for collections or topics", which confuses the issue. Even when you are using the Autosuggest, you are still not really searching for "topics", ultimately you are searching for data collections. Curiously, "Data" is not really mentioned on the front page of the UI. Suggest changing this phrase to "Type text to search for data"

### Acceptance Criteria
Keyword search placeholder text reads "Type text to search for data".

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by macrouch** [comment]
@Vinitvh for now just work on the other issue you commented on, I'm going to leave this one open if someone else comes around, since we only have a handful of new issues for Hacktoberfest

**Comment by Nisarg-Chokshi** [comment]
Hello @macrouch Can I work on this ?

**Comment by macrouch** [comment]
@Nisarg-Chokshi its all yours!

**Comment by chiragkhatri19** [comment]
Hey @macrouch  , I am getting started in open source and would like to be assigned this or any future issues. I appreciate any help you can give me.

**Comment by macrouch** [comment]
@Nisarg-Chokshi I'm very sorry, I got a little too eager last week creating these issues. We want to handle this issue in a different way than we current have this issue written. I'm going to close for now
