### ISSUE TITLE
Should this project have open issues?

### ISSUE THREAD

**Issue by Brantron** [nasa/earthdata-search#300]
I would assume other people would like to contribute to this project. Are there any issues which can be opened?

**Comment by mreese84** [comment]
@Brantron we currently use a separate system for issue tracking. If you would like to submit issues against Earthdata Search Client you can click the "feedback" button in the top right corner of the application to open a ticket for our dev team to consider.

We welcome contributions from the community though! Please consult our [contribution guidelines](https://github.com/nasa/earthdata-search/blob/master/CONTRIBUTING.md) if you would like to contribute.

**Comment by axle07** [comment]
I'd love to participate, but without a sense of the bugs that need addressing or features that would be useful, it's difficult to contribute.

**Comment by mreese84** [comment]
As mentioned above, we use a separate system for issue tracking. However, we have an effort underway to determine how to best manage issues within that system with our open sourced projects. We have a meeting set for later this month to kick that effort off.
