### ISSUE TITLE
Create a new portal for PO.DAAC

### ISSUE THREAD

**Issue by lewismc** [nasa/earthdata-search#689]
Talking with @littleidiot40 I was talked through the creation of a new portal. This issue will provide the basis for creation of a new PO.DAAC portal which will reside at https://search.earthdata.nasa.gov/portal/podaac/search

PR coming up!

**Comment by lewismc** [comment]
Hi Folks, within the README it states 
```
Modify line 37 of config/services.yml to contain your Earthdata Login application's client ID
```
Line 37 is blank... what is line 37 referring to? Thanks

**Comment by mreese84** [comment]
Once your portal is up and running, you'll be able to point the portal to _any_ CMR environment with a URL parameter. For example, https://search.earthdata.nasa.gov/search?cmr_env=uat

**Comment by lewismc** [comment]
@mgangl it should be mentioned here as well that we (PO.DAAC) are working with the EDSC team to ensure that the project is capable of accepting contributions. There are some timing constraints which @mreese84 and I discussed so we will be working to ensure that the correct work gets done at the correct time.
Thanks for chiming in.

**Comment by lewismc** [comment]
Merged in https://github.com/nasa/earthdata-search/pull/746
