### ISSUE TITLE
Clarify order of commands in README 

### ISSUE THREAD

**Issue by lewismc** [nasa/earthdata-search#740]
The README states the following
```
Run

    bin/setup

Note: This command will take a long time to run

### Application configuration

Review `config/application.yml` and update values as necessary

#### (Optional) Earthdata Login (URS) Configuration
```
I have an issue with this, if you just execute ```bin/setup```, you are WARNed that you should copy ```config/application.yml.example``` and ```config/database.yml.example``` to _formal_ files at ```config/application.yml``` and ```config/database.yml``` respectively. This means that once I do that, I then need to go back and configure the deployment however this should be done **_prior_** to me running ```bin/setup```!

Additionally, I would strongly suggest that we encourage folks to sign up for URS rather than stating it as an optional step. The reason I say this, is as follows. Say they first run ```bin/setup```, then go and create deployment-specific manifestations of ```config/application.yml``` and ```config/database.yml```, based on the logic of the README, they still would again have to go back and add configure URS details if they have not already done that. This seems somewhat convoluted and I think it should be streamlined. 

If we can agree, then I'll go ahead and get a quick PR submitted. Any thoughts?

**Comment by macrouch** [comment]
I am **not** on board with adding `application.yml` and `database.yml` to the repo. Adding them introduces the possibility of leaking sensitive credentials on github. 

`bin/setup` does give a warning it those files don't exist, but it creates them for you with a setup that works for local development. And even if you need to change the values for some reason, `bin/setup` is not required for new values to take effect. 

Values in `application.yml` and `database.yml` can be updated at any time. You just have to restart Rails in order to pick up new values. So going back in after the initial setup completes is perfectly normal. 

URS is optional because of the requirements to get a URS account added to the necessary group to correctly work with the CMR.

**Comment by lewismc** [comment]
Thanks @mreese84 @macrouch for comments.

> I am not on board with adding application.yml and database.yml to the repo. Adding them introduces the possibility of leaking sensitive credentials on github.

No-one has suggested adding either of those files. The point I was making is that the README should prompt a user to create and edit those files prior to executing ```./bin/setup```. Does that make sense?

> Values in application.yml and database.yml can be updated at any time. You just have to restart Rails in order to pick up new values.

This validates my initial comment. Why not prompt a user to edit them prior to attempting a set up rather than making an assumption that they know what rails is and that they have it installed and that they know the correct command line tasks to restart rails correctly? From a usability standpoint, getting it right from the beginning is easier and streamlines what I need to do. Does this make sense? Additionally, the README does not include information on how to restart rails... so this is not an optimal situation either.

> URS is optional because of the requirements to get a URS account added to the necessary group to correctly work with the CMR.

Who are the necessary group? Am I included in that Group? Is anyone outside of EED contractors? Is Joe Blow who is a potential future contributor? Is a software engineer for a new AIST or ACCESS-funded project which wishes to develop EDSC? My opinion is that people should be encouraged to sign up for URS accounts in order to unlock advanced application functionality. Sooner or later users will want to work with the functionality anyways... 

Thanks folks, I'll go ahead and submit a documentation PR for README. Please post any further thoughts you have. I appreciate it.

**Comment by lewismc** [comment]
PING

**Comment by mreese84** [comment]
@lewismc, I don't have good advise for you on the URS stuff. That's something I need to talk through with ESDIS and other EED folks. Once we have a clearer direction we can revisit the URS issue. I'm fine with the other stuff though.

**Comment by mreese84** [comment]
Closing this issue as we have a brand new readme with the new React app now merged into master.
