### ISSUE TITLE
Error executing command docker-compose run web bundle exec rake db:setup

### ISSUE THREAD

**Issue by lewismc** [nasa/earthdata-search#743]
## Environment
macOS High Sierra v10.13.6
Docker for Mac v2.0.0.0-mac81 (29211)

## Issue
The Docker build eventually fails for above environment as follows
```
./bin/setup
...
== Preparing database (development and test environments) ==
    $ docker-compose run web bundle exec rake db:setup
Starting earthdata-search_db_1 ... done
Could not locate Gemfile or .bundle/ directory
Exiting: Error executing command docker-compose run web bundle exec rake db:setup
```
I've been picking the docker-compose build apart and haven't yet found any solution.

**Comment by lewismc** [comment]
Is anyone else able to replicate this? This is blocking me building the actual deployment at the moment.

**Comment by macrouch** [comment]
We never ran into this problem, the 2 commands in the readme were all we had to do to get running.

I assumed it was related to your other issue with file sharing on OS X. Have you tried moving your project to your user directory?

**Comment by lewismc** [comment]
Thanks @macrouch I've documented this as https://github.com/nasa/earthdata-search/wiki/FAQ's#install-location-for-earthdata-search-on-os-x
